#!/bin/bash
#==============================================================================#
# This is a script that removes all the intermediate files created in case the #
# script exits prematurely.                                                    #
#------------------------------------------------------------------------------#
# Author: Dustin Morado                                                        #
# Written: February 19th 2011                                                  #
# Contact: Dustin.Morado@uth.tmc.edu                                           #
#------------------------------------------------------------------------------#
# Arguments: $1= image stack file <filename.st>                                #
#==============================================================================#

# make a variable for the base etc.
base=$(basename $1 .st)

# remove all the basename files
rm -f ${base}* 2>&1 > /dev/null

# remove any comscripts
rm -f *.com 2>&1 > /dev/null

# this should always get removed but in case not
rm -f rotationfile fidfile 2>&1 > /dev/null

# remove any folders that weren't removed earlier
rm -rf clean raw raptor1 raptor2 2>&1 > /dev/null

# Move back the original files and delete the holding folder
mv Final_files/* . && rmdir Final_files 2>&1 > /dev/null
