#!/bin/bash
#==============================================================================#
# This is a script that uses the header command to create files to extract the #
# rotation angle and pixelsize to be used in the automation of eTomo.          #
#------------------------------------------------------------------------------#
# Author: Dustin Morado                                                        #
# Written: February 2nd 2011                                                   #
# Revision: 1.1 February 18th 2011 (Handling JEOL headers)                     #
# Revision: 1.2 February 22nd 2011 (Moving to awk from cut)
# Contact: Dustin.Morado@uth.tmc.edu                                           #
#------------------------------------------------------------------------------#
# Arguments: $1= image stack file <filename.st>                                #
#            $2= fiducial size in nm <integer>                                 #
#==============================================================================#

# First test to see what type of stack file is used
if [ `file $1 | grep BASIC -c` -eq 1 ]; then
    mode="FEI"
elif [ `file $1 | grep CCP4 -c` -eq 1 ]; then
    mode="JEOL"
else
    printf "%b" "Unknown file type please send bug report!\n" 2>&1
    exit 1
fi

# Handle FEI stacks
if [ $mode = "FEI" ]; then
    header $1 > headerfile
    grep 'Number' headerfile | awk '{ print $7 " " $8 }' > imagesize
    grep 'Tilt axis' headerfile | awk '{ print $6 }' > rotationfile
    grep 'Pixel size' headerfile | awk '{ print $6 }' > pixelfile
    rm headerfile
fi

# Handle JEOL stacks
if [ $mode = "JEOL" ]; then
    header $1 > headerfile
    grep 'Number' headerfile | awk '{ print $7 " " $8 }' > imagesize
    X=$(grep Angstroms headerfile | awk '{ print $4 }')
    Y=$(grep Angstroms headerfile | awk '{ print $5 }')
    Z=$(grep Angstroms headerfile | awk '{ print $6 }')
    if [ ! "$X" = "$Y" ] || [ ! "$Y" = "$Z" ]; then
        printf "%b" "irregular pixel spacing! aborting\n" 2>&1
        exit 1
    fi
    echo "scale=3; $X/10" | bc -l > pixelfile
    grep 'Tilt axis' headerfile | awk '{ print $5 }' | \
        sed -e 's:,::' > rotationfile
    rm headerfile
fi
pixel=$(cat pixelfile)
fidint=$(echo "scale=0; $2/$pixel" | bc -l)
echo $fidint > fidfile
rm pixelfile
