#!/bin/bash
#==============================================================================#
# This is a script that monitors the disk space for the used file and returns  #
# a value which can be used to stop the script currently running               #
#------------------------------------------------------------------------------#
# Author: Dustin Morado                                                        #
# Written: February 7th 2011                                                   #
# Contact: Dustin.Morado@uth.tmc.edu                                           #
#------------------------------------------------------------------------------#
# Arguments: $1= image stack file <filename.st>                                #
#            $2= limit when to return error exit <integer>                     #
#==============================================================================#

# Make variables for the arguments
file=$1
limit=$2

# Get the current disk space percentage.
puse=$(df -h $file | awk '{ print $5 }' | sed 1d | cut -d% -f1)

if [ $puse -lt $limit ]; then
    exit 0
else
    exit 3
fi
