-- tomoauto global configuration.
-- @module Config
-- @author Dustin Morado
-- @license GPLv3
-- @release 0.2.30

local Config = {}
local io, string, table = io, string, table
local Utils = require('tomoauto_utils')

local function needs_update(value)
  return type(value) == 'string' and string.match(value, 'TOMOAUTO{[%w_-]+}')
end

local function update_value(mrc, value)
  local mrc_key = string.match(value, 'TOMOAUTO{([%w_-]+)}')
  local mrc_value = mrc[mrc_key]
  return string.gsub(value, 'TOMOAUTO{[%w_-]+}', mrc_value)
end

local function write_IMOD_command_file (self, mrc)
  local command_filename = update_value(mrc, self.Name)
  Utils.backup(command_filename)
  local command_file = io.open(command_filename, 'w')

  for _, entry in ipairs(self) do
    local use, value = self[entry].use, self[entry].value
    if entry == 'CommandLine' then
      command_file:write(value .. '\n')
    elseif use and needs_update(value) then
      local updated_value = update_value(mrc, value)
      command_file:write(entry .. '\t' .. updated_value .. '\n')
    elseif use and type(value) == 'table' then
      command_file:write(entry .. '\t' .. table.concat(value, ',') .. '\n')
    elseif use and value then
      command_file:write(entry .. '\t' .. value .. '\n')
    elseif use then
      command_file:write(entry .. '\n')
    end
  end

  command_file:close()
end

local function write_shell_command_file (self, mrc)
  local command_filename = update_value(mrc, self.Name)
  Utils.backup(command_filename)
  local command_file = io.open(command_filename, 'w')

  for _, entry in ipairs(self) do
    local use, value = self[entry].use, self[entry].value
    if use and needs_update(value) then
      local updated_value = update_value(mrc, value)
      command_file:write(updated_value .. '\n')
    elseif use and value then
      command_file:write(value .. '\n')
    end
  end

  command_file:close()
end

local function write_EOF_command_file (self, filename)
  local command_filename = update_value(mrc, self.Name)
  Utils.backup(command_filename)
  local command_file = io.open(command_filename, 'w')

  for _, entry in ipairs(self) do
    local use, value = self[entry].use, self[entry].value
    if use and needs_update(value) then
      local updated_value = update_value(mrc, value)
      command_file:write(updated_value .. '\n')
    elseif use and value then
      command_file:write(value .. '\n')
    end
  end

  command_file:write('EOF\n')
  command_file:close()
end

local function run_IMOD_command_file (self, mrc)
  local command_filename = update_value(mrc, self.Name)
  if Utils.is_file(command_filename) then
    return Utils.run('submfg ' .. command_filename)
  else
    self:write(mrc)
    return Utils.run('submfg ' .. command_filename)
  end
end

local function run_shell_command_file (self, mrc)
  local command_filename = update_value(mrc, self.Name)
  if Utils.is_file(command_filename) then
    return Utils.run('bash ' .. command_filename)
  else
    self:write(mrc)
    return Utils.run('bash ' .. command_filename)
  end
end

local function clear_config (self)
  for _, entry in ipairs(self) do
    if self[entry].use and entry ~= 'CommandLine' then
      self[entry].use = false
    end
  end
end

local function update_config (self, new_config)
  for entry, new_config_table in pairs(new_config) do
    if self[entry] and type(self[entry]) == 'table' then
      local new_use = new_config_table.use
      local new_value = new_config_table.value
      self[entry].use = new_use
      self[entry].value = new_value
    end
  end
end

function Config:load_local_config (filename)
  local sandbox = {}
  local chunk = loadfile(filename, 't', sandbox)
  if not chunk then
    error('ERROR: Config:load_local_config: Could not load file.\n')
  end

  chunk()
  for variable, new_config in pairs(sandbox) do
    if self[variable] and type(self[variable]) == 'table' then
      self[variable]:update(new_config)
    end
  end
end

Config.ccderaser = {
  Name = 'TOMOAUTO{basename}_ccderaser.com',
  'CommandLine',
  CommandLine = { use = true, value = '$ccderaser -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.st' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_fixed.st' },
  'PieceListFile',
  PieceListFile = { use = false, value = nil },
  'OverlapsForModel',
  OverlapsForModel = { use = false, value = nil },
  'FindPeaks',
  FindPeaks = { use = true, value = nil },
  'PeakCriterion',
  PeakCriterion = { use = true, value = 10.0 },
  'DiffCriterion',
  DiffCriterion = { use = true, value = 8.0 },
  'GrowCriterion',
  GrowCriterion = { use = true, value = 4.0 },
  'ScanCriterion',
  ScanCriterion = { use = true, value = 3.0 },
  'MaximumRadius',
  MaximumRadius = { use = true, value = 4.2 },
  'GiantCriterion',
  GiantCriterion = { use = true, value = 12.0 },
  'ExtraLargeRadius',
  ExtraLargeRadius = { use = true, value = 8.0 },
  'BigDiffCriterion',
  BigDiffCriterion = { use = true, value = 19.0 },
  'MaxPixelsInDiffPatch',
  MaxPixelsInDiffPatch = { use = false, value = nil },
  'OuterRadius',
  OuterRadius = { use = false, value = nil },
  'AnnulusWidth',
  AnnulusWidth = { use = true, value = 2.0 },
  'XYScanSize',
  XYScanSize = { use = true, value = 100 },
  'EdgeExclusionWidth',
  EdgeExclusionWidth = { use = true, value = 4 },
  'PointModel',
  PointModel = { use = true, value = 'TOMOAUTO{basename}_peak.mod' },
  'ModelFile',
  ModelFile = { use = false, value = nil },
  'LineObjects',
  LineObjects = { use = false, value = nil },
  'BoundaryObjects',
  BoundaryObjects = { use = false, value = nil },
  'AllSectionObjects',
  AllSectionObjects = { use = false, value = nil },
  'CircleObjects',
  CircleObjects = { use = false, value = nil },
  'BetterRadius',
  BetterRadius = { use = false, value = nil },
  'ExpandCircleIterations',
  ExpandCircleIterations = { use = false, value = nil },
  'MergePatches',
  MergePatches = { use = false, value = nil },
  'BorderSize',
  BorderSize = { use = true, value = 2 },
  'PolynomialOrder',
  PolynomialOrder = { use = true, value = 2 },
  'ExcludeAdjacent',
  ExcludeAdjacent = { use = false, value = nil },
  'TrialMode',
  TrialMode = { use = false, value = nil },
  'Verbose',
  Verbose = { use = false, value = nil },
  'ProcessID',
  ProcessID = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.tiltxcorr = {
  Name = 'TOMOAUTO{basename}_tiltxcorr.com',
  'CommandLine',
  CommandLine = { use = true, value = '$tiltxcorr -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.st' },
  'PieceListFile',
  PieceListFile = { use = false, value = nil },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}.prexf' },
  'RotationAngle',
  RotationAngle = { use = true, value = 'TOMOAUTO{tilt_axis_angle}' },
  'FirstTiltAngle',
  FirstTiltAngle = { use = false, value = nil },
  'TiltIncrement',
  TiltIncrement = { use = false, value = nil },
  'TiltFile',
  TiltFile = { use = true, value = 'TOMOAUTO{basename}.rawtlt' },
  'TiltAngles',
  TiltAngles = { use = false, value = nil },
  'AngleOffset',
  AngleOffset = { use = false, value = nil },
  'ReverseOrder',
  ReverseOrder = { use = false, value = nil },
  'FilterRadius1',
  FilterRadius1 = { use = false, value = nil },
  'FilterRadius2',
  FilterRadius2 = { use = true, value = 0.25 },
  'FilterSigma1',
  FilterSigma1 = { use = true, value = 0.03 },
  'FilterSigma2',
  FilterSigma2 = { use = true, value = 0.05 },
  'ExcludeCentralPeak',
  ExcludeCentralPeak = { use = false, value = nil },
  'CentralPeakExclusionCriteria',
  CentralPeakExclusionCriteria = { use = false, value = nil },
  'ShiftLimitsXandY',
  ShiftLimitsXandY = { use = false, value = nil },
  'RectangularLimits',
  RectangularLimits = { use = false, value = nil },
  'CorrelationCoefficient',
  CorrelationCoefficient = { use = false, value = nil },
  'BordersInXandY',
  BordersInXandY = { use = false, value = nil },
  'XMinAndMax',
  XMinAndMax = { use = false, value = nil },
  'YMinAndMax',
  YMinAndMax = { use = false, value = nil },
  'BoundaryModel',
  BoundaryModel = { use = false, value = nil },
  'BoundaryObject',
  BoundaryObject = { use = false, value = nil },
  'BinningToApply',
  BinningToApply = { use = false, value = nil },
  'AntialiasFilter',
  AntialiasFilter = { use = false, value = nil },
  'LeaveTiltAxisShifted',
  LeaveTiltAxisShifted = { use = false, value = nil },
  'PadsInXandY',
  PadsInXandY = { use = false, value = nil },
  'TapersInXandY',
  TapersInXandY = { use = false, value = nil },
  'StartingEndingViews',
  StartingEndingViews = { use = false, value = nil },
  'SkipViews',
  SkipViews = { use = false, value = nil },
  'BreakAtViews',
  BreakAtViews = { use = false, value = nil },
  'CumulativeCorrelation',
  CumulativeCorrelation = { use = false, value = nil },
  'AbsoluteCosineStretch',
  AbsoluteCosineStretch = { use = false, value = nil },
  'NoCosineStretch',
  NoCosineStretch = { use = false, value = nil },
  'IterateCorrelations',
  IterateCorrelations = { use = false, value = nil },
  'SearchMagChanges',
  SearchMagChanges = { use = false, value = nil },
  'ViewsWithMagChanges',
  ViewsWithMagChanges = { use = false, value = nil },
  'MagnificationLimits',
  MagnificationLimits = { use = false, value = nil },
  'SizeOfPatchesXandY',
  SizeOfPatchesXandY = { use = false, value = nil },
  'NumberOfPatchesXandY',
  NumberOfPatchesXandY = { use = false, value = nil },
  'OverlapPatchesXandY',
  OverlapPatchesXandY = { use = false, value = nil },
  'SeedModel',
  SeedModel = { use = false, value = nil },
  'SeedObject',
  SeedObject = { use = false, value = nil },
  'LengthAndOverlap',
  LengthAndOverlap = { use = false, value = nil },
  'PrealignmentTransformFile',
  PrealignmentTransformFile = { use = false, value = nil },
  'ImagesAreBinned',
  ImagesAreBinned = { use = false, value = nil },
  'UnalignedSizeXandY',
  UnalignedSizeXandY = { use = false, value = nil },
  'FindWarpTransforms',
  FindWarpTransforms = { use = false, value = nil },
  'RawAndAlignedPair',
  RawAndAlignedPair = { use = false, value = nil },
  'AppendToWarpFile',
  AppendToWarpFile = { use = false, value = nil },
  'TestOutput',
  TestOutput = { use = false, value = nil },
  'VerboseOutput',
  VerboseOutput = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.xftoxg = {
  Name = 'TOMOAUTO{basename}_xftoxg.com',
  'CommandLine',
  CommandLine = { use = true, value = '$xftoxg -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.prexf' },
  'GOutputFile',
  GOutputFile = { use = true, value = 'TOMOAUTO{basename}.prexg' },
  'NumberToFit',
  NumberToFit = { use = true, value = 0 },
  'ReferenceSection',
  ReferenceSection = { use = false, value = nil },
  'OrderOfPolynomialFit',
  OrderOfPolynomialFit = { use = false, value = nil },
  'HybridFits',
  HybridFits = { use = false, value = nil },
  'RangeOfAnglesInAverage',
  RangeOfAnglesInAverage = { use = false, value = nil },
  'RobustFit',
  RobustFit = { use = false, value = nil },
  'KFactorScaling',
  KFactorScaling = { use = false, value = nil },
  'MaximumIterations',
  MaximumIterations = { use = false, value = nil },
  'IterationParams',
  IterationParams = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.xfalign = {
  Name = 'TOMOAUTO{basename}_xftoxg.com',
  'CommandLine',
  CommandLine = { use = true, value = '$xfalign -StandardInput' },
  'InputImageFile',
  InputImagefile = { use = true, value = 'TOMOAUTO{abspath}' },
  'OutputTransformFile',
  OutputTransformFile = { use = true, value = 'TOMOAUTO{basename}.xf' },
  'SizeToAnalyze',
  SizeToAnalyze = { use = false, value = nil },
  'OffsetToSubarea',
  OffsetToSubarea = { use = false, value = nil },
  'EdgeToIgnore',
  EdgeToIgnore = { use = false, value = nil },
  'ReduceByBinning',
  ReduceByBinning = { use = true, value = 4 },
  'FilterParameters',
  FilterParameters = { use = false, value = nil },
  'SobelFilter',
  SobelFilter = { use = false, value = nil },
  'ParametersToSearch',
  ParametersToSearch = { use = false, value = nil },
  'LimitsOnSearch',
  LimitsOnSearch = { use = false, value = nil },
  'BilinearInterpolation',
  BilinearInterpolation = { use = false, value = nil },
  'CorrelationCoefficient',
  CorrelationCoefficient = { use = false, value = nil },
  'LocalPatchSize',
  LocalPatchSize = { use = false, value = nil },
  'ReferenceFile',
  ReferenceFile = { use = false, value = nil },
  'PreCrossCorrelation',
  PreCrossCorrelation = { use = true, value = nil },
  'XcorrFilter',
  XcorrFilter = { use = true, value = { 0.01, 0.02, 0, 0.3 } },
  'InitialTransform',
  InitialTransform = { use = false, value = nil },
  'WarpPatchSizeXandY',
  WarpPatchSizeXandY = { use = false, value = nil },
  'BoundaryModel',
  BoundaryModel = { use = false, value = nil },
  'ShiftLimitsForWarp',
  ShiftLimitsForWarp = { use = false, value = nil },
  'SkipSections',
  SkipSections = { use = false, value = nil },
  'BreakAtSections',
  BreakAtSections = { use = false, value = nil },
  'PairedImages',
  PairedImages = { use = false, value = nil },
  'TomogramAverages',
  TomogramAverages = { use = false, value = nil },
  'DifferenceOutput',
  DifferenceOutput = { use = false, value = nil },
  'SectionsNumberedFromOne',
  SectionsNumberedFromOne = { use = false, value = nil },
  'PID',
  PID = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.xyzproj = {
  Name = 'TOMOAUTO{basename}_xyzproj.com',
  'CommandLine',
  CommandLine = { use = true, value = '$xyzproj -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.ali' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_driftcorr.mrc' },
  'AxisToTiltAround',
  AxisToTiltAround = { use = true, value = 'Y' },
  'XMinAndMax',
  XMinAndMax = { use = false, value = nil },
  'YMinAndMax',
  YMinAndMax = { use = false, value = nil },
  'ZMinAndMax',
  ZMinAndMax = { use = false, value = nil },
  'StartEndIncAngle',
  StartEndIncAngle = { use = false, value = nil },
  'ModeToOutput',
  ModeToOutput = { use = false, value = nil },
  'WidthToOutput',
  WidthToOutput = { use = false, value = nil },
  'AddThenMultiply',
  AddThenMultiply = { use = false, value = nil },
  'FillValue',
  FillValue = { use = false, value = nil },
  'ConstantScaling',
  ConstantScaling = { use = false, value = nil },
  'TiltFile',
  TiltFile = { use = false, value = nil },
  'FirstTiltAngle',
  FirstTiltAngle = { use = false, value = nil },
  'TiltIncrement',
  TiltIncrement = { use = false, value = nil },
  'TiltAngles',
  TiltAngles = { use = false, value = nil },
  'FullAreaAtTilt',
  FullAreaAtTilt = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}
Config.prenewstack = {
  Name = 'TOMOAUTO{basename}_prenewstack.com',
  'CommandLine',
  CommandLine = { use = true, value = '$newstack -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.st' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}.preali' },
  'FileOfInputs',
  FileOfInputs = { use = false, value = nil },
  'FileOfOutputs',
  FileOfOutputs = { use = false, value = nil },
  'SplitStartingNumber',
  SplitStartingNumber = { use = false, value = nil },
  'AppendExtension',
  AppendExtension = { use = false, value = nil },
  'SectionsToRead',
  SectionsToRead = { use = false, value = nil },
  'NumberedFromOne',
  NumberedFromOne = { use = false, value = nil },
  'ExcludeSections',
  ExcludeSections = { use = false, value = nil },
  'TwoDirectionTiltSeries',
  TwoDirectionTiltSeries = { use = false, value = nil },
  'SkipSectionIncrement',
  SkipSectionIncrement = { use = false, value = nil },
  'NumberToOutput',
  NumberToOutput = { use = false, value = nil },
  'ReplaceSections',
  ReplaceSections = { use = false, value = nil },
  'BlankOutput',
  BlankOutput = { use = false, value = nil },
  'OffsetsInXandY',
  OffsetsInXandY = { use = false, value = nil },
  'ApplyOffsetsFirst',
  ApplyOffsetsFirst = { use = false, value = nil },
  'TransformFile',
  TransformFile = { use = true, value = 'TOMOAUTO{basename}.prexg' },
  'UseTransformLines',
  UseTransformLines = { use = false, value = nil },
  'OneTrasformPerFile',
  OneTrasformPerFile = { use = false, value = nil },
  'RotateByAngle',
  RotateByAngle = { use = false, value = nil },
  'ExpandByFactor',
  ExpandByFactor = { use = false, value = nil },
  'ShrinkByFactor',
  ShrinkByFactor = { use = false, value = nil },
  'AntialiasFilter',
  AntialiasFilter = { use = false, value = nil },
  'BinByFactor',
  BinByFactor = { use = false, value = nil },
  'DistortionField',
  DistortionField = { use = false, value = nil },
  'ImagesAreBinned',
  ImagesAreBinned = { use = false, value = nil },
  'UseFields',
  UseFields = { use = false, value = nil },
  'GradientFile',
  GradientFile = { use = false, value = nil },
  'AdjustOrigin',
  AdjustOrigin = { use = false, value = nil },
  'LinearInterpolation',
  LinearInterpolation = { use = false, value = nil },
  'NearestNeighbor',
  NearestNeighbor = { use = false, value = nil },
  'SizeToOutputInXandY',
  SizeToOutputInXandY = { use = false, value = nil },
  'ModeToOutput',
  ModeToOutput = { use = false, value = nil },
  'BytesSignedInOutput',
  BytesSignedInOutput = { use = false, value = nil },
  'StripExtraHeader',
  StripExtraHeader = { use = false, value = nil },
  'FloatDensities',
  FloatDensities = { use = false, value = nil },
  'MeanAndStandardDeviation',
  MeanAndStandardDeviation = { use = false, value = nil },
  'ContrastBlackWhite',
  ContrastBlackWhite = { use = false, value = nil },
  'ScaleMinAndMax',
  ScaleMinAndMax = { use = false, value = nil },
  'MultiplyAndAdd',
  MultiplyAndAdd = { use = false, value = nil },
  'FillValue',
  FillValue = { use = false, value = nil },
  'TaperAtFill',
  TaperAtFill = { use = false, value = nil },
  'MemoryLimit',
  MemoryLimit = { use = false, value = nil },
  'TestLimits',
  TestLimits = { use = false, value = nil },
  'VerboseOutput',
  VerboseOutput = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.RAPTOR = {
  Name = 'TOMOAUTO{basename}_RAPTOR.com',
  'CommandLine',
  CommandLine = { use = true, value = '$RAPTOR -StandardInput' },
  'RaptorExecPath',
  RaptorExecPath = { use = true, value = '/usr/local/IMOD/bin/realbin/' },
  'InputPath',
  InputPath = { use = true, value = 'TOMOAUTO{dirname}' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.preali' },
  'OutputPath',
  OutputPath = { use = true,
                 value = 'TOMOAUTO{currentdir}/TOMOAUTO{basename}_RAPTOR' },
  'Diameter',
  Diameter = { use = true, value = 'TOMOAUTO{fiducial_diameter_px}' },
  'WhiteMarkers',
  WhiteMarkers = { use = false, value = nil },
  'MarkersPerImage',
  MarkersPerImage = { use = false, value = nil },
  'AnglesInHeader',
  AnglesInHeader = { use = true, value = nil },
  'Binning',
  Binning = { use = false, value = nil },
  'Reconstruction',
  Reconstruction = { use = false, value = nil },
  'Thickness',
  Thickness = { use = false, value = nil },
  'Orient',
  Orient = { use = false, value = nil },
  'TrackingOnly',
  TrackingOnly = { use = false, value = nil },
  'xRay',
  xRay = { use = false, value = nil },
  'Verbose',
  Verbose = { use = false, value = nil },
  'MaxDistanceCandidate',
  MaxDistanceCandidate = { use = false, value = nil },
  'MinNeighborsMRF',
  MinNeighborsMRF = { use = false, value = nil },
  'RollOffMRF',
  RollOffMRF = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.autofidseed = {
  Name = 'TOMOAUTO{basename}_autofidseed.com',
  'CommandLine',
  CommandLine = { use = true, value = '$autofidseed -StandardInput' },
  'TrackCommandFile',
  TrackCommandFile = { use = true, value = 'TOMOAUTO{basename}_beadtrack.com'},
  'AppendToSeedModel',
  AppendToSeedModel = { use = false, value = nil },
  'MinGuessNumBeads',
  MinGuessNumBeads = { use = false, value = nil },
  'MinSpacing',
  MinSpacing = { use = true, value = 0.85 },
  'BeadSize',
  BeadSize = { use = false, value = nil },
  'AdjustSizes',
  AdjustSizes = { use = false, value = nil },
  'PeakStorageFraction',
  PeakStorageFraction = { use = true, value = 1.0 },
  'FindBeadOptions',
  FindBeadOptions = { use = false, value = nil },
  'NumberOfSeedViews',
  NumberOfSeedViews = { use = false, value = nil },
  'BoundaryModel',
  BoundaryModel = { use = false, value = nil },
  'ExcludeInsideAreas',
  ExcludeInsideAreas = { use = false, value = nil },
  'BordersInXandY',
  BordersInXandY = { use = false, value = nil },
  'TwoSurfaces',
  TwoSurfaces = { use = false, value = nil },
  'TargetNumberOfBeads',
  TargetNumberOfBeads = { use = true, value = 20 },
  'TargetDensityOfBeads',
  TargetDensityOfBeads = { use = false, value = nil },
  'MaxMajorToMinorRatio',
  MaxMajorToMinorRatio = { use = false, value = nil },
  'ElongatedPointsAllowed',
  ElongatedPointsAllowed = { use = false, value = nil },
  'ClusteredPointsAllowed',
  ClusteredPointsAllowed = { use = false, value = nil },
  'LowerTargetForClustered',
  LowerTargetForClustered = { use = false, value = nil },
  'SubareaSize',
  SubareaSize = { use = false, value = nil },
  'SortAreasMinNumAndSize',
  SortAreasMinNumAndSize = { use = false, value = nil },
  'IgnoreSurfaceData',
  IgnoreSurfaceData = { use = false, value = nil },
  'DropTracks',
  DropTracks = { use = false, value = nil },
  'PickSeedOptions',
  PickSeedOptions = { use = false, value = nil },
  'RemoveTempFiles',
  RemoveTempFiles = { use = false, value = nil },
  'OutputSeedModel',
  OutputSeedModel = { use = false, value = nil },
  'InfoFile',
  InfoFile = { use = false, value = nil },
  'TemporaryDirectory',
  TemporaryDirectory = { use = false, value = nil },
  'LeaveTempFiles',
  LeaveTempFiles = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.beadtrack = {
  Name = 'TOMOAUTO_{basename}_beadtrack.com',
  'CommandLine',
  CommandLine = { use = true, value = '$beadtrack -StandardInput' },
  'InputSeedModel',
  InputSeedModel = { use = true, value = 'TOMOAUTO{basename}.seed' },
  'OutputModel',
  OutputModel = { use = true, value = 'TOMOAUTO{basename}.fid' },
  'ImageFile',
  ImageFile = { use = true, value = 'TOMOAUTO{basename}.preali' },
  'PieceListFile',
  PieceListFile = { use = false, value = nil },
  'PrealignTransformFile',
  PrealignTransformFile = { use = true, value = 'TOMOAUTO{basename}.prexg' },
  'ImagesAreBinned',
  ImagesAreBinned = { use = false, value = nil },
  'XYZOutputFile',
  XYZOutputFile = { use = false, value = nil },
  'ElongationOuptutFile',
  ElongationOuptutFile = { use = false, value = nil },
  'SkipViews',
  SkipViews = { use = false, value = nil },
  'RotationAngle',
  RotationAngle = { use = true, value = 'TOMOAUTO{tilt_axis_angle}' },
  'SeparateGroup',
  SeparateGroup = { use = false, value = nil },
  'FirstTiltAngle',
  FirstTiltAngle = { use = false, value = nil },
  'TiltIncrement',
  TiltIncrement = { use = false, value = nil },
  'TiltFile',
  TiltFile = { use = true, value = 'TOMOAUTO{basename}.rawtlt' },
  'TiltAngles',
  TiltAngles = { use = false, value = nil },
  'TiltDefaultGrouping',
  TiltDefaultGrouping = { use = true, value = 5 },
  'TiltNondefaultGrouping',
  TiltNondefaultGrouping = { use = false, value = nil },
  'MagDefaultGrouping',
  MagDefaultGrouping = { use = true, value = 5 },
  'MagNondefaultGrouping',
  MagNondefaultGrouping = { use = false, value = nil },
  'RotDefaultGrouping',
  RotDefaultGrouping = { use = true, value = 1 },
  'RotNondefaultGrouping',
  RotNondefaultGrouping = { use = false, value = nil },
  'MinViewsForTiltalign',
  MinViewsForTiltalign = { use = true, value = 4 },
  'CentroidRadius',
  CentroidRadius = { use = false, value = nil },
  'BeadDiameter',
  BeadDiameter = { use = true, value = 'TOMOAUTO{fiducial_diameter_px}' },
  'MedianForCentroid',
  MedianForCentroid = { use = false, value = nil },
  'LightBeads',
  LightBeads = { use = false, value = nil },
  'FillGaps',
  FillGaps = { use = true, value = nil },
  'MaxGapSize',
  MaxGapSize = { use = true, value = 5 },
  'MinTiltRangeToFindAxis',
  MinTiltRangeToFindAxis = { use = true, value = 10.0 },
  'MinTiltRangeToFindAngles',
  MinTiltRangeToFindAngles = { use = false, value = nil },
  'BoxSizeXandY',
  BoxSizeXandY = { use = true, value = { 72, 72 } },
  'RoundsOfTracking',
  RoundsOfTracking = { use = true, value = 20 },
  'MaxViewsInAlign',
  MaxViewsInAlign = { use = false, value = nil },
  'RestrictViewsOnRound',
  RestrictViewsOnRound = { use = false, value = nil },
  'UnsplitFirstRound',
  UnsplitFirstRound = { use = false, value = nil },
  'LocalAreaTracking',
  LocalAreaTracking = { use = true, value = 1 },
  'LocalAreaTargetSize',
  LocalAreaTargetSize = { use = true, value = 1000 },
  'MinBeadsInArea',
  MinBeadsInArea = { use = true, value = 3 },
  'MinOverlapBeads',
  MinOverlapBeads = { use = true, value = 3 },
  'TrackObjectsTogether',
  TrackObjectsTogether = { use = false, value = nil },
  'MaxBeadsToAverage',
  MaxBeadsToAverage = { use = true, value = 4 },
  'SobelFilterCentering',
  SobelFilterCentering = { use = true, value = nil },
  'KernelSigmaForSobel',
  KernelSigmaForSobel = { use = true, value = 1.75 },
  'AverageBeadsForSobel',
  AverageBeadsForSobel = { use = false, value = nil },
  'InterpolationType',
  InterpolationType = { use = false, value = nil },
  'PointsToFitMaxAndMin',
  PointsToFitMaxAndMin = { use = true, value = { 7, 3 } },
  'DensityRescueFractionAndSD',
  DensityRescueFractionAndSD = { use = true, value = { 0.6, 1.0 } },
  'DistanceRescueCriterion',
  DistanceRescueCriterion = { use = true, value = 10.0 },
  'RescueRelaxationDensityAndDistance',
  RescueRelaxationDensityAndDistance = { use = true, value = { 0.7, 0.9 } },
  'PostFitRescueResidual',
  PostFitRescueResidual = { use = true, value = 2.5 },
  'DensityRelaxationPostFit',
  DensityRelaxationPostFit = { use = true, value = 0.9 },
  'MaxRescueDistance',
  MaxRescueDistance = { use = true, value = 2.5 },
  'ResidualsToAnalyzeMaxAndMin',
  ResidualsToAnalyzeMaxAndMin = { use = true, value = { 9, 5 } },
  'DeletionCriterionMinAndSD',
  DeletionCriterionMinAndSD = { use = true, value = { 0.04, 2.0 } },
  'BoxOutputFile',
  BoxOutputFile = { use = false, value = nil },
  'SnapshotViews',
  SnapshotViews = { use = false, value = nil },
  'SaveAllPointsAreaRound',
  SaveAllPointsAreaRound = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.tiltalign = {
  Name = 'TOMOAUTO{basenam}_tiltalign.com',
  'CommandLine',
  CommandLine = { use = true, value = '$tiltalign -StandardInput' },
  'ModelFile',
  ModelFile = { use = true, value = 'TOMOAUTO{basename}.fid' },
  'ImageFile',
  ImageFile = { use = true, value = 'TOMOAUTO{basename}.preali' },
  'ImageSizeXandY',
  ImageSizeXandY = { use = false, value = nil },
  'ImageOriginXandY',
  ImageOriginXandY = { use = false, value = nil },
  'ImagePixelSizeXandY',
  ImagePixelSizeXandY = { use = false, value = nil },
  'ImagesAreBinned',
  ImagesAreBinned = { use = false, value = nil },
  'OutputModelFile',
  OutputModelFile = { use = false, value = nil },
  'OutputResidualFile',
  OutputResidualFile = { use = false, value = nil },
  'OutputModelAndResidual',
  OutputModelAndResidual = { use = true, value = 'TOMOAUTO{basename}.resid' },
  'OutputTopBotResiduals',
  OutputTopBotResiduals = { use = false, value = nil },
  'OutputFidXYZFile',
  OutputFidXYZFile = { use = true, value = 'TOMOAUTO{basename}_fid.xyz' },
  'OutputTiltFile',
  OutputTiltFile = { use = true, value = 'TOMOAUTO{basename}.tlt' },
  'OutputUnadjustedTiltFile',
  OutputUnadjustedTiltFile = { use = false, value = nil },
  'OutputXAxisTiltFile',
  OutputXAxisTiltFile = { use = true, value = 'TOMOAUTO{basename}.xtilt' },
  'OutputTransformFile',
  OutputTransformFile = { use = true, value = 'TOMOAUTO{basename}.tltxf' },
  'OutputZFactorFile',
  OutputZFactorFile = { use = false, value = 'TOMOAUTO{basename}.zfac' },
  'IncludeStartEndInc',
  IncludeStartEndInc = { use = false, value = nil },
  'IncludeList',
  IncludeList = { use = false, value = nil },
  'ExcludeList',
  ExcludeList = { use = false, value = nil },
  'RotationAngle',
  RotationAngle = { use = true, value = 'TOMOAUTO{tilt_axis_angle}' },
  'SeparateGroup',
  SeparateGroup = { use = false, value = '1-TOMOAUTO{bidirectional_section}' },
  'FirstTiltAngle',
  FirstTiltAngle = { use = false, value = nil },
  'TiltIncrement',
  TiltIncrement = { use = false, value = nil },
  'TiltFile',
  TiltFile = { use = false, value = nil },
  'TiltAngles',
  TiltAngles = { use = false, value = nil },
  'AngleOffset',
  AngleOffset = { use = false, value = nil },
  'ProjectionStretch',
  ProjectionStretch = { use = false, value = nil },
  'BeamTiltOption',
  BeamTiltOption = { use = true, value = 0 },
  'FixedOrInitialBeamTilt',
  FixedOrInitialBeamTilt = { use = false, value = nil },
  'RotOption',
  RotOption = { use = true, value = 3 },
  'RotDefaultGrouping',
  RotDefaultGrouping = { use = true, value = 5 },
  'RotNondefaultGrouping',
  RotNondefaultGrouping = { use = false, value = nil },
  'RotationFixedView',
  RotationFixedView = { use = false, value = nil },
  'LocalRotOption',
  LocalRotOption = { use = false, value = 3 },
  'LocalRotDefaultGrouping',
  LocalRotDefaultGrouping = { use = false, value = 6 },
  'LocalRotNondefaultGrouping',
  LocalRotNondefaultGrouping = { use = false, value = nil },
  'TiltOption',
  TiltOption = { use = true, value = 5 },
  'TiltFixedView',
  TiltFixedView = { use = false, value = nil },
  'TiltSecondFixedView',
  TiltSecondFixedView = { use = false, value = nil },
  'TiltDefaultGrouping',
  TiltDefaultGrouping = { use = true, value = 5 },
  'TiltNondefaultGrouping',
  TiltNondefaultGrouping = { use = false, value = nil },
  'LocalTiltOption',
  LocalTiltOption = { use = false, value = 5 },
  'LocalTiltFixedView',
  LocalTiltFixedView = { use = false, value = nil },
  'LocalTiltSecondFixedView',
  LocalTiltSecondFixedView = { use = false, value = nil },
  'LocalTiltDefaultGrouping',
  LocalTiltDefaultGrouping = { use = false, value = 6 },
  'LocalTiltNondefaultGrouping',
  LocalTiltNondefaultGrouping = { use = false, value = nil },
  'MagReferenceView',
  MagReferenceView = { use = true, value = 1 },
  'MagOption',
  MagOption = { use = true, value = 3 },
  'MagDefaultGrouping',
  MagDefaultGrouping = { use = true, value = 4 },
  'MagNondefaultGrouping',
  MagNondefaultGrouping = { use = false, value = nil },
  'LocalMagReferenceView',
  LocalMagReferenceView = { use = false, value = 1 },
  'LocalMagOption',
  LocalMagOption = { use = false, value = 3 },
  'LocalMagDefaultGrouping',
  LocalMagDefaultGrouping = { use = false, value = 7 },
  'LocalMagNondefaultGrouping',
  LocalMagNondefaultGrouping = { use = false, value = nil },
  'CompReferenceView',
  CompReferenceView = { use = false, value = nil },
  'CompOption',
  CompOption = { use = false, value = nil },
  'CompDefaultGrouping',
  CompDefaultGrouping = { use = false, value = nil },
  'CompNondefaultGrouping',
  CompNondefaultGrouping = { use = false, value = nil },
  'XStretchOption',
  XStretchOption = { use = true, value = 0 },
  'XStretchDefaultGrouping',
  XStretchDefaultGrouping = { use = true, value = 7 },
  'XStretchNondefaultGrouping',
  XStretchNondefaultGrouping = { use = false, value = nil },
  'LocalXStretchOption',
  LocalXStretchOption = { use = false, value = 3 },
  'LocalXStretchDefaultGrouping',
  LocalXStretchDefaultGrouping = { use = false, value = 11 },
  'LocalXStretchNondefaultGrouping',
  LocalXStretchNondefaultGrouping = { use = false, value = nil },
  'SkewOption',
  SkewOption = { use = true, value = 0 },
  'SkewDefaultGrouping',
  SkewDefaultGrouping = { use = true, value = 11 },
  'SkewNondefaultGrouping',
  SkewNondefaultGrouping = { use = false, value = nil },
  'LocalSkewOption',
  LocalSkewOption = { use = false, value = 3 },
  'LocalSkewDefaultGrouping',
  LocalSkewDefaultGrouping = { use = false, value = 11 },
  'LocalSkewNondefaultGrouping',
  LocalSkewNondefaultGrouping = { use = false, value = nil },
  'XTiltOption',
  XTiltOption = { use = false, value = nil },
  'XTiltDefaultGrouping',
  XTiltDefaultGrouping = { use = false, value = nil },
  'XTiltNondefaultGrouping',
  XTiltNondefaultGrouping = { use = false, value = nil },
  'LocalXTiltOption',
  LocalXTiltOption = { use = false, value = nil },
  'LocalXTiltDefaultGrouping',
  LocalXTiltDefaultGrouping = { use = false, value = nil },
  'LocalXTiltNondefaultGrouping',
  LocalXTiltNondefaultGrouping = { use = false, value = nil },
  'ResidualReportCriterion',
  ResidualReportCriterion = { use = true, value = 3.0 },
  'SurfacesToAnalyze',
  SurfacesToAnalyze = { use = true, value = 2 },
  'MetroFactor',
  MetroFactor = { use = true, value = 0.25 },
  'MaximumCycles',
  MaximumCycles = { use = true, value = 1000 },
  'RobustFitting',
  RobustFitting = { use = true, value = nil },
  'WeightWholeTracks',
  WeightWholeTracks = { use = false, value = nil },
  'KFactorScaling',
  KFactorScaling = { use = true, value = 1.0 },
  'WarnOnRobustFailure',
  WarnOnRobustFailure = { use = false, value = nil },
  'MinWeightGroupSizes',
  MinWeightGroupSizes = { use = false, value = nil },
  'AxisZShift',
  AxisZShift = { use = true, value = 0.0 },
  'ShiftZFromOriginal',
  ShiftZFromOriginal = { use = true, value = nil },
  'AxisXShift',
  AxisXShift = { use = false, value = nil },
  'LocalAlignments',
  LocalAlignments = { use = false, value = nil },
  'OutputLocalFile',
  OutputLocalFile = { use = false, value = nil },
  'NumberOfLocalPatchesXandY',
  NumberOfLocalPatchesXandY = { use = false, value = { 5, 5 } },
  'TargetPatchSizeXandY',
  TargetPatchSizeXandY = { use = false, value = nil },
  'MinSizeOrOverlapXandY',
  MinSizeOrOverlapXandY = { use = true, value = { 0.5, 0.5 } },
  'MinFidsTotalAndEachSurface',
  MinFidsTotalAndEachSurface = { use = true, value = { 8, 3} },
  'FidXYZCoordinates',
  FidXYZCoordinates = { use = false, value = nil },
  'LocalOutputOptions',
  LocalOutputOptions = { use = false, value = { 1, 0, 1 } },
  'RotMapping',
  RotMapping = { use = false, value = nil },
  'LocalRotMapping',
  LocalRotMapping = { use = false, value = nil },
  'TiltMapping',
  TiltMapping = { use = false, value = nil },
  'LocalTiltMapping',
  LocalTiltMapping = { use = false, value = nil },
  'MagMapping',
  MagMapping = { use = false, value = nil },
  'LocalMagMapping',
  LocalMagMapping = { use = false, value = nil },
  'CompMapping',
  CompMapping = { use = false, value = nil },
  'XStretchMapping',
  XStretchMapping = { use = false, value = nil },
  'LocalXStretchMapping',
  LocalXStretchMapping = { use = false, value = nil },
  'SkewMapping',
  SkewMapping = { use = false, value = nil },
  'LocalSkewMapping',
  LocalSkewMapping = { use = false, value = nil },
  'XTiltMapping',
  XTiltMapping = { use = false, value = nil },
  'LocalXTiltMapping',
  LocalXTiltMapping = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.xfproduct = {
  Name = 'TOMOAUTO{basename}_xfproduct.com',
  'CommandLine',
  CommandLine = { use = true, value = '$xfproduct -StandardInput' },
  'InputFile1',
  InputFile1 = { use = true, value = 'TOMOAUTO{basename}.prexg' },
  'InputFile2',
  InputFile2 = { use = true, value = 'TOMOAUTO{basename}.tltxf' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_fid.xf' },
  'ScaleShifts',
  ScaleShifts = { use = false, value = nil },
  'OneXformToMultiply',
  OneXformToMultiply = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.newstack = {
  Name = 'TOMOAUTO{basename}_newstack.com',
  'CommandLine',
  CommandLine = { use = true, value = '$newstack -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.st' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}.ali' },
  'FileOfInputs',
  FileOfInputs = { use = false, value = nil },
  'FileOfOutputs',
  FileOfOutputs = { use = false, value = nil },
  'SplitStartingNumber',
  SplitStartingNumber = { use = false, value = nil },
  'AppendExtension',
  AppendExtension = { use = false, value = nil },
  'SectionsToRead',
  SectionsToRead = { use = false, value = nil },
  'NumberedFromOne',
  NumberedFromOne = { use = false, value = nil },
  'ExcludeSections',
  ExcludeSections = { use = false, value = nil },
  'TwoDirectionTiltSeries',
  TwoDirectionTiltSeries = { use = false, value = nil },
  'SkipSectionIncrement',
  SkipSectionIncrement = { use = false, value = nil },
  'NumberToOutput',
  NumberToOutput = { use = false, value = nil },
  'ReplaceSections',
  ReplaceSections = { use = false, value = nil },
  'BlankOutput',
  BlankOutput = { use = false, value = nil },
  'OffsetsInXandY',
  OffsetsInXandY = { use = false, value = nil },
  'ApplyOffsetsFirst',
  ApplyOffsetsFirst = { use = false, value = nil },
  'TransformFile',
  TransformFile = { use = true, value = 'TOMOAUTO{basename}.xf' },
  'UseTransformLines',
  UseTransformLines = { use = false, value = nil },
  'OneTrasformPerFile',
  OneTrasformPerFile = { use = false, value = nil },
  'RotateByAngle',
  RotateByAngle = { use = false, value = nil },
  'ExpandByFactor',
  ExpandByFactor = { use = false, value = nil },
  'ShrinkByFactor',
  ShrinkByFactor = { use = false, value = nil },
  'AntialiasFilter',
  AntialiasFilter = { use = false, value = nil },
  'BinByFactor',
  BinByFactor = { use = false, value = nil },
  'DistortionField',
  DistortionField = { use = false, value = nil },
  'ImagesAreBinned',
  ImagesAreBinned = { use = false, value = nil },
  'UseFields',
  UseFields = { use = false, value = nil },
  'GradientFile',
  GradientFile = { use = false, value = nil },
  'AdjustOrigin',
  AdjustOrigin = { use = true, value = nil },
  'LinearInterpolation',
  LinearInterpolation = { use = false, value = nil },
  'NearestNeighbor',
  NearestNeighbor = { use = false, value = nil },
  'SizeToOutputInXandY',
  SizeToOutputInXandY = { use = false, value = nil },
  'ModeToOutput',
  ModeToOutput = { use = false, value = nil },
  'BytesSignedInOutput',
  BytesSignedInOutput = { use = false, value = nil },
  'StripExtraHeader',
  StripExtraHeader = { use = false, value = nil },
  'FloatDensities',
  FloatDensities = { use = false, value = nil },
  'MeanAndStandardDeviation',
  MeanAndStandardDeviation = { use = false, value = nil },
  'ContrastBlackWhite',
  ContrastBlackWhite = { use = false, value = nil },
  'ScaleMinAndMax',
  ScaleMinAndMax = { use = false, value = nil },
  'MultiplyAndAdd',
  MultiplyAndAdd = { use = false, value = nil },
  'FillValue',
  FillValue = { use = false, value = nil },
  'TaperAtFill',
  TaperAtFill = { use = true, value = { 1, 0 } },
  'MemoryLimit',
  MemoryLimit = { use = false, value = nil },
  'TestLimits',
  TestLimits = { use = false, value = nil },
  'VerboseOutput',
  VerboseOutput = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.ctfplotter = {
  Name = 'TOMOAUTO{basename}_ctfplotter.com',
  'CommandLine',
  CommandLine = { use = true, value = '$ctfplotter -StandardInput' },
  'InputStack',
  InputStack = { use = true, value = 'TOMOAUTO{basename}.st' },
  'AngleFile',
  AngleFile = { use = true, value = 'TOMOAUTO{basename}.tlt' },
  'InvertTiltAngles',
  InvertTiltAngles = { use = false, value = nil },
  'OffsetToAdd',
  OffsetToAdd = { use = false, value = nil },
  'ConfigFile',
  ConfigFile = { use = true,
    value = '/usr/local/ImodCalib/CTFnoise/K24Kbackground/' ..
            'polara-K2-4k-2014.ctf' },
  'DefocusFile',
  DefocusFile = { use = true, value = 'TOMOAUTO{basename}.defocus' },
  'AxisAngle',
  AxisAngle = { use = true, value = 'TOMOAUTO{tilt_axis_angle}' },
  'PSResolution',
  PSResolution = { use = false, value = nil },
  'TileSize',
  TileSize = { use = false, value = nil },
  'Voltage',
  Voltage = { use = true, value = 300 },
  'MaxCacheSize',
  MaxCacheSize = { use = false, value = nil },
  'SphericalAberration',
  SphericalAberration = { use = true, value = 2.0 },
  'DefocusTol',
  DefocusTol = { use = false, value = nil },
  'PixelSize',
  PixelSize = { use = true, value = 'TOMOAUTO{pixel_size_nm}' },
  'AmplitudeContrast',
  AmplitudeContrast = { use = true, value = 0.10 },
  'ExpectedDefocus',
  ExpectedDefocus = { use = true, value = 'TOMOAUTO{defocus}' },
  'LeftDefTol',
  LeftDefTol = { use = false, value = nil },
  'RightDefTol',
  RightDefTol = { use = false, value = nil },
  'AngleRange',
  AngleRange = { use = true, value = { -40.0, 40.0 } },
  'AutoFitRangeAndStep',
  AutoFitRangeAndStep = { use = true, value = { 0.0, 0.0 } },
  'FrequencyRangeToFit',
  FrequencyRangeToFit = { use = true, value = { 0.05, 0.225 } },
  'VaryExponentInFit',
  VaryExponentInFit = { use = true, value = nil },
  'SaveAndExit',
  SaveAndExit = { use = true, value = nil },
  'DebugLevel',
  DebugLevel = { use = false, value = nil },
  'Parameter',
  Parameter = { use = false, value = nil },
  'FocalPairDefocusOffset',
  FocalPairDefocusOffset = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.ctfphaseflip = {
  Name = 'TOMOAUTO{basename}_ctfphaseflip.com',
  'CommandLine',
  CommandLine = { use = true, value = '$ctfphaseflip -StandardInput' },
  'InputStack',
  InputStack = { use = true, value = 'TOMOAUTO{basename}.ali' },
  'OutputFileName',
  OutputFileName = { use = true, value = 'TOMOAUTO{basename}_ctfcorr.ali' },
  'AngleFile',
  AngleFile = { use = true, value = 'TOMOAUTO{basename}.tlt' },
  'InvertTiltAngles',
  InvertTiltAngles = { use = false, value = nil },
  'DefocusFile',
  DefocusFile = { use = true, value = 'TOMOAUTO{basename}.defocus' },
  'TransformFile',
  TransformFile = { use = true, value = 'TOMOAUTO{basename}.xf' },
  'DefocusTol',
  DefocusTol = { use = true, value = 200 },
  'MaximumStripWidth',
  MaximumStripWidth = { use = false, value = nil },
  'InterpolationWidth',
  InterpolationWidth = { use = true, value = 20 },
  'PixelSize',
  PixelSize = { use = true, value = 'TOMOAUTO{pixel_size_nm}' },
  'Voltage',
  Voltage = { use = true, value = 300 },
  'SphericalAberration',
  SphericalAberration = { use = true, value = 2.0 },
  'AmplitudeContrast',
  AmplitudeContrast = { use = true, value = 0.10 },
  'StartingEndingViews',
  StartingEndingViews = { use = false, value = nil },
  'TotalViews',
  TotalViews = { use = false, value = nil },
  'BoundaryInfoFile',
  BoundaryInfoFile = { use = false, value = nil },
  'AxisAngle',
  AxisAngle = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.xfmodel = {
  Name = 'TOMOAUTO{basename}xfmodel.com',
  'CommandLine',
  CommandLine = { use = true, value = '$xfmodel -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.fid' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_erase.fid' },
  'ImageFile',
  ImageFile = { use = false, value = nil },
  'PieceListFile',
  PieceListFile = { use = false, value = nil },
  'AllZhaveTransforms',
  AllZhaveTransforms = { use = false, value = nil },
  'CenterInXandY',
  CenterInXandY = { use = false, value = nil },
  'TranslationOnly',
  TranslationOnly = { use = false, value = nil },
  'RotationTranslation',
  RotationTranslation = { use = false, value = nil },
  'MagRotTrans',
  MagRotTrans = { use = false, value = nil },
  'SectionsToAnalyze',
  SectionsToAnalyze = { use = false, value = nil },
  'SingleSection',
  SingleSection = { use = false, value = nil },
  'FullReportMeanAndMax',
  FullReportMeanAndMax = { use = false, value = nil },
  'PrealignTransforms',
  PrealignTransforms = { use = false, value = nil },
  'EditTransforms',
  EditTransforms = { use = false, value = nil },
  'XformsToApply',
  XformsToApply = { use = true, value = 'TOMOAUTO{basename}.tltxf' },
  'UseTransformLine',
  UseTransformLine = { use = false, value = nil },
  'ChunkSizes',
  ChunkSizes = { use = false, value = nil },
  'BackTransform',
  BackTransform = { use = false, value = nil },
  'ScaleShifts',
  ScaleShifts = { use = false, value = nil },
  'DistortionField',
  DistortionField = { use = false, value = nil },
  'BinningOfImages',
  BinningOfImages = { use = false, value = nil },
  'GradientFile',
  GradientFile = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.gold_ccderaser = {
  Name = 'TOMOAUTO{basename}_gold_ccderaser.com',
  'CommandLine',
  CommandLine = { use = true, value = '$ccderaser -StandardInput' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.ali' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_erase.ali' },
  'PieceListFile',
  PieceListFile = { use = false, value = nil },
  'OverlapsForModel',
  OverlapsForModel = { use = false, value = nil },
  'FindPeaks',
  FindPeaks = { use = false, value = nil },
  'PeakCriterion',
  PeakCriterion = { use = false, value = nil },
  'DiffCriterion',
  DiffCriterion = { use = false, value = nil },
  'GrowCriterion',
  GrowCriterion = { use = false, value = nil },
  'ScanCriterion',
  ScanCriterion = { use = false, value = nil },
  'MaximumRadius',
  MaximumRadius = { use = false, value = nil },
  'GiantCriterion',
  GiantCriterion = { use = false, value = nil },
  'ExtraLargeRadius',
  ExtraLargeRadius = { use = false, value = nil },
  'BigDiffCriterion',
  BigDiffCriterion = { use = false, value = nil },
  'MaxPixelsInDiffPatch',
  MaxPixelsInDiffPatch = { use = false, value = nil },
  'OuterRadius',
  OuterRadius = { use = false, value = nil },
  'AnnulusWidth',
  AnnulusWidth = { use = false, value = nil },
  'XYScanSize',
  XYScanSize = { use = false, value = nil },
  'EdgeExclusionWidth',
  EdgeExclusionWidth = { use = false, value = nil },
  'PointModel',
  PointModel = { use = false, value = nil },
  'ModelFile',
  ModelFile = { use = true, value = 'TOMOAUTO{basename}_erase.fid' },
  'LineObjects',
  LineObjects = { use = false, value = nil },
  'BoundaryObjects',
  BoundaryObjects = { use = false, value = nil },
  'AllSectionObjects',
  AllSectionObjects = { use = false, value = nil },
  'CircleObjects',
  CircleObjects = { use = true, value = '/' },
  'BetterRadius',
  BetterRadius = { use = true, value = 13.25 },
  'ExpandCircleIterations',
  ExpandCircleIterations = { use = false, value = nil },
  'MergePatches',
  MergePatches = { use = true, value = nil },
  'BorderSize',
  BorderSize = { use = false, value = nil },
  'PolynomialOrder',
  PolynomialOrder = { use = true, value = 0 },
  'ExcludeAdjacent',
  ExcludeAdjacent = { use = true, value = nil },
  'TrialMode',
  TrialMode = { use = false, value = nil },
  'Verbose',
  Verbose = { use = false, value = nil },
  'ProcessID',
  ProcessID = { use = false, value = nil },
  'ParameterFile',
  ParameterFile = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.tilt = {
  Name = 'TOMOAUTO{basename}_tilt.com',
  'CommandLine',
  CommandLine = { use = true, value = '$tilt -StandardInput' },
  'InputProjections',
  InputProjections = { use = true, value = 'TOMOAUTO{basename}.ali' },
  'OutputFile',
  OutputFile = { use = true, value = 'TOMOAUTO{basename}_full.rec' },
  'RecFileToReproject',
  RecFileToReproject = { use = false, value = nil },
  'ProjectModel',
  ProjectModel = { use = false, value = nil },
  'BaseRecFile',
  BaseRecFile = { use = false, value = nil },
  'ActionIfGPUFails',
  ActionIfGPUFails = { use = true, value = { 1, 2 } },
  'AdjustOrigin',
  AdjustOrigin = { use = true, value = nil },
  'ANGLES',
  ANGLES = { use = false, value = nil },
  'BaseNumViews',
  BaseNumViews = { use = false, value = nil },
  'BoundaryInfoFile',
  BoundaryInfoFile = { use = false, value = nil },
  'COMPFRACTION',
  COMPFRACTION = { use = false, value = nil },
  'COMPRESS',
  COMPRESS = { use = false, value = nil },
  'ConstrainSign',
  ConstrainSign = { use = false, value = nil },
  'COSINTERP',
  COSINTERP = { use = false, value = nil },
  'DENSWEIGHT',
  DENSWEIGHT = { use = false, value = nil },
  'DONE',
  DONE = { use = false, value = nil },
  'EXCLUDELIST2',
  EXCLUDELIST2 = { use = false, value = nil },
  'FlatFilterFraction',
  FlatFilterFraction = { use = false, value = nil },
  'FBPINTERP',
  FBPINTERP = { use = false, value = nil },
  'FULLIMAGE',
  FULLIMAGE = { use = false, value = nil },
  'IMAGEBINNED',
  IMAGEBINNED = { use = true, value = 1 },
  'INCLUDE',
  INCLUDE = { use = false, value = nil },
  'LOCALFILE',
  LOCALFILE = { use = false, value = nil },
  'LOCALSCALE',
  LOCALSCALE = { use = false, value = nil },
  'LOG',
  LOG = { use = true, value = 0.0 },
  'MASK',
  MASK = { use = false, value = nil },
  'MinMaxMean',
  MinMaxMean = { use = false, value = nil },
  'MODE',
  MODE = { use = false, value = nil },
  'OFFSET',
  OFFSET = { use = false, value = nil },
  'PARALLEL',
  PARALLEL = { use = false, value = nil },
  'PERPENDICULAR',
  PERPENDICULAR = { use = true, value = nil },
  'RADIAL',
  RADIAL = { use = true, value = { 0.35, 0.05 } },
  'REPLICATE',
  REPLICATE = { use = false, value = nil },
  'REPROJECT',
  REPROJECT = { use = false, value = nil },
  'RotateBy90',
  RotateBy90 = { use = false, value = nil },
  'SCALE',
  SCALE = { use = true, value = { 0.0, 700.0 } },
  'SHIFT',
  SHIFT = { use = true, value = { 0.0, 0.0 } },
  'SIRTIterations',
  SIRTIterations = { use = false, value = nil },
  'SIRTSubtraction',
  SIRTSubtraction = { use = false, value = nil },
  'SLICE',
  SLICE = { use = false, value = nil },
  'StartingIteration',
  StartingIteration = { use = false, value = nil },
  'SUBSETSTART',
  SUBSETSTART = { use = true, value = { 0, 0 } },
  'SubtractFromBase',
  SubtractFromBase = { use = false, value = nil },
  'THICKNESS',
  THICKNESS = { use = true, value = 1200 },
  'TILTFILE',
  TILTFILE = { use = true, value = 'TOMOAUTO{basename}.tlt' },
  'TITLE',
  TITLE = { use = false, value = nil },
  'TOTALSLICES',
  TOTALSLICES = { use = false, value = nil },
  'UseGPU',
  UseGPU = { use = false, value = nil },
  'ViewsToReproject',
  ViewsToReproject = { use = false, value = nil },
  'VertBoundaryFile',
  VertBoundaryFile = { use = false, value = nil },
  'VertSliceOutputFile',
  VertSliceOutputFile = { use = false, value = nil },
  'VertForSIRTInput',
  VertForSIRTInput = { use = false, value = nil },
  'WeightAngleFile',
  WeightAngleFile = { use = false, value = nil },
  'WeightFile',
  WeightFile = { use = false, value = nil },
  'WIDTH',
  WIDTH = { use = false, value = nil },
  'XAXISTILT',
  XAXISTILT = { use = false, value = nil },
  'XMinAndMaxReproj',
  XMinAndMaxReproj = { use = false, value = nil },
  'XTILTFILE',
  XTILTFILE = { use = false, value = nil },
  'XTILTINTERP',
  XTILTINTERP = { use = false, value = nil },
  'YMinAndMaxReproj',
  YMinAndMaxReproj = { use = false, value = nil },
  'ZFACTORFILE',
  ZFACTORFILE = { use = false, value = nil },
  'ZMinAndMaxReproj',
  ZMinAndMaxReproj = { use = false, value = nil },
  'DebugOutput',
  DebugOutput = { use = false, value = nil },
  'InternalSIRTSlices',
  InternalSIRTSlices = { use = false, value = nil },
  'ParameterFile',
  ParameterFile = { use = false, value = nil },
  write = write_IMOD_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.tomo3d = {
  Name = 'TOMOAUTO{basename}_tomo3d.com',
  'CommandLine',
  CommandLine = { use = true, value = '#!/bin/bash\ntomo3d \\' },
  'TiltFile',
  TiltFile = { use = true, value = '-a TOMOAUTO{basename}.tlt \\' },
  'InputFile',
  InputFile = { use = true, value = '-i TOMOAUTO{basename}.ali \\' },
  'AngleOffset',
  AngleOffset = { use = false, value = '-A offset \\' },
  'IOBuffers',
  IOBuffers = { use = false, value = '-b n,m \\' },
  'CacheBlock',
  CacheBlock = { use = false, value = '-C n \\' },
  'ConstrainOutputVolume',
  ConstrainOutputVolume = { use = false, value = '-c \\' },
  'VectorExtensions',
  VectorExtensions = { use = false, value = '-e avx/sse/none \\' },
  'OverwriteOutputVolume',
  OverwriteOutputVolume = { use = false, value = '-f \\' },
  'HyperThreading',
  HyperThreading = { use = false, value = '-H \\' },
  'Interpolation',
  Interpolation = { use = false, value = '-I on/off \\' },
  'LogReconstruction',
  LogReconstruction = { use = false, value = '-L \\' },
  'Iterations',
  Iterations = { use = false, value = '-l iter \\' },
  'MemoryLimit',
  MemoryLimit = { use = false, value = '-M memlimit \\' },
  'HammingFrequency',
  HammingFrequency = { use = true, value = '-m 0.35 \\' },
  'InvertHandedness',
  InvertHandedness = { use = false, value = '-n \\' },
  'SinogramOffset',
  SinogramOffset = { use = false, value = '-O densoffset \\' },
  'OutputVolume',
  OutputVolume = { use = true, value = '-o TOMOAUTO{basename}_tomo3d.rec \\' },
  'SinogramProjections',
  SinogramProjections = { use = false, value = '-P n \\' },
  'ProcessRows',
  ProcessRows = { use = false, value = 'R n \\' },
  'ResumeSIRTVolume',
  ResumeSIRTVolume = { use = false, value = '-r tomogram \\' },
  'SIRT',
  SIRT = { use = false, value = '-S \\' },
  'SplitFactor',
  SplitFactor = { use = false, value = '-s splitf \\' },
  'Threading',
  Threading = { use = false, value = '-t threads \\' },
  'Verbosity',
  Verbosity = { use = false, value = '-v level \\' },
  'Weighting',
  Weighting = { use = false, value = '-w on/off \\' },
  'Width',
  Width = { use = false, value = '-x width \\' },
  'Depth',
  Depth = { use = false, value = '-y y1,y2 \\' },
  'Height',
  Height = { use = true, value = '-z 1200 \\' },
  write = write_shell_command_file,
  run = run_IMOD_command_file,
  clear = clear_config,
  update = update_config,
}

Config.MOTIONCORR = {
  Name = 'TOMOAUTO{basename}_MOTIONCORR.com',
  'CommandLine',
  CommandLine = { use = true, value = '#!/bin/bash\ndosefgpu_driftcorr \\' },
  'InputStack',
  InputStack = { use = true, value = 'TOMOAUTO{basename}.mrc' },
  'CropOffsetX',
  CropOffsetX = { use = false, value = '-crx 0 \\' },
  'CropOffsetY',
  CropOffsetY = { use = false, value = '-cry 0 \\' },
  'CropDimensionX',
  CropDimensionX = { use = false, value = '-cdx 0 \\' },
  'CropDimensionY',
  CropDimensionY = { use = false, value = '-cdy 0 \\' },
  'Binning',
  Binning = { use = false, value = '-bin 1 \\' },
  'AlignmentFirstFrame',
  AlignmentFirstFrame = { use = false, value = '-nst 0 \\' },
  'AlignmentLastFrame',
  AlignmentLastFrame = { use = false, value = '-ned 0 \\' },
  'SumFirstFrame',
  SumFirstFrame = { use = false, value = '-nss 0 \\' },
  'SumLastFrame',
  SumLastFrame = { use = false, value = '-nes 0 \\' },
  'GPUDeviceID',
  GPUDeviceID = { use = false, value = '-gpu 0 \\' },
  'BFactor',
  BFactor = { use = true, value = '-bft 300 \\' },
  'PeakBox',
  PeakBox = { use = false, value = '-pbx 96 \\' },
  'FrameOffset',
  FrameOffset = { use = true, value = '-fod 1 \\' },
  'NoisePeakRadius',
  NoisePeakRadius = { use = false, value = '-nps 0 \\' },
  'ErrorThreshold',
  ErrorThreshold = { use = false, value = '-kit 1.0 \\' },
  'GainReferenceFile',
  GainReferenceFile = { use = false, value = '-fgr FileName.mrc \\' },
  'DarkReferenceFile',
  DarkReferenceFile = { use = false, value = '-fdr FileName.mrc \\' },
  'SaveUncorrectedSum',
  SaveUncorrectedSum = { use = false, value = '-srs 0 \\' },
  'SaveUncorrectedStack',
  SaveUncorrectedStack = { use = false, value = '-ssr 0 \\' },
  'SaveCorrectedStack',
  SaveCorrectedStack = { use = false, value = '-ssc 0 \\' },
  'SaveCorrelationMap',
  SaveCorrelationMap = { use = false, value = '-scc 0 \\' },
  'SaveLog',
  SaveLog = { use = false, value = '-slg 1 \\' },
  'AlignToMiddleFrame',
  AlignToMiddleFrame = { use = false, value = '-atm 1 \\' },
  'SaveQuickResults',
  SaveQuickResults = { use = true, value = '-dsp 0 \\' },
  'UncorrectedSumOutput',
  UncorrectedSumOutput = { use = false, value = '-frs FileName.mrc \\' },
  'UncorrectedStackOutput',
  UncorrectedStackOutput = { use = false, value = '-frt FileName.mrc \\' },
  'CorrectedSumOutput',
  CorrectedSumOutput = { use = true,
                         value = '-fcs TOMOAUTO{basename}_driftcorr.mrc \\' },
  'CorrectedStackOutput',
  CorrectedStackOutput = { use = false, value = '-fct FileName.mrc \\' },
  'CorrelationMapOutput',
  CorrelationMapOutput = { use = false, value = '-fcm FileName.mrc \\' },
  'LogFileOutput',
  LogFileOutput = { use = true,
                    value = '-flg TOMOAUTO{basename}_driftcorr.log \\' },
  write = write_shell_command_file,
  run = run_shell_command_file,
  clear = clear_config,
  update = update_config,
}

Config.CTFFIND4 = {
  Name = 'TOMOAUTO{basename}_CTFFIND4.com',
  'CommandLine',
  CommandLine = { use = true, value = '#!/bin/bash\nctffind << EOF' },
  'InputFile',
  InputFile = { use = true, value = 'TOMOAUTO{basename}.mrc' },
  'DiagnosticOutput',
  DiagnosticOutput = { use = true, value = 'TOMOAUTO{basename}.ctf' },
  'PixelSize',
  PixelSize = { use = true, value = 'TOMOAUTO{pixel_size_A}' },
  'AccelerationVoltage',
  AccelerationVoltage = { use = true, value = 300 },
  'ShpericalAberration',
  ShpericalAberration = { use = true, value = 2.0 },
  'AmplitudeContrast',
  AmplitudeContrast = { use = true, value = 0.10 },
  'BoxSize',
  BoxSize = { use = true, value = 256 },
  'MinimumResolution',
  MinimumResolution = { use = true, value = 50.0 },
  'MaximumResolution',
  MaximumResolution = { use = true, value = 10.0 },
  'MinimumDefocus',
  MinimumDefocus = { use = true, value = 10000.0 },
  'MaximumDefocus',
  MaximumDefocus = { use = true, value = 90000.0 },
  'DefocusSearchStep',
  DefocusSearchStep = { use = true, value = 5000.0 },
  'AstigmatismTolerance',
  AstigmatismTolerance = { use = true, value = 100.0 },
  'AdditionalPhaseShift',
  AdditionalPhaseShift = { use = true, value = 'no' },
  'MinimumPhaseShift',
  MinimumPhaseShift = { use = false, value = nil },
  'MaximumPhaseShift',
  MaximumPhaseShift = { use = false, value = nil },
  'PhaseShiftSearchStep',
  PhaseShiftSearchStep = { use = false, value = nil },
  write = write_EOF_command_file,
  run = run_shell_command_file,
  clear = clear_config,
  update = update_config,
}

return Config
